name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      # Only rebuild website when docs have changed
      - 'README.md'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'docs/**'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v5
      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy
          python -m pip install .["docs"]

      - name: Deploy docs
        run: mkdocs gh-deploy --force -f docs/mkdocs.yml
